Issue 12# - relação ManyToMany de user-roles
lmtsufape/Patrimonio pull request #13
Opened 2023-12-06 16:36 UTC by ThaysonScript

2023-12-11 19:56 UTC, Rener1 requested changes

2023-12-11 19:56 UTC, Rener1 commented on app/Http/Controllers/ServidorController.php
> +                'role_id' => $request->role_id
Remover linha `'role_id' => $request->role_id`, as roles não são mais definidas como relação one to many e sim many to many.

2023-12-11 19:56 UTC, Rener1 commented on app/Http/Controllers/ServidorController.php
> +                'role_id' => $request->role_id,
Alterar a role fora do update também usando o método sync().

2023-12-11 19:56 UTC, Rener1 commented on database/migrations/2023_12_06_153856_create_user_role_table.php
Lembrando da ordem alfabética na nomenclatura da tabela intermediária.

![Captura de tela 2023-12-11 163732](https://github.com/lmtsufape/Patrimonio/assets/55724549/58a4207d-b114-4639-b5d5-f37fbcf80464)
Renomear para role_user.

2023-12-11 19:56 UTC, Rener1 commented on app/Models/User.php
> +        if (!is_array($tipo)) {
Seria mais fácil definir logo que o parâmetro $tipo é uma array diretamente, `public function hasAnyRoles(array $tipo)`, evitando a verificação abaixo `if (!is_array($tipo))`.

2023-12-13 18:33 UTC, jvictorcordeiro approved these changes

2023-12-13 18:41 UTC, Rener1 approved these changes

2023-12-13 18:41 UTC, merged